language: go

install: false

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - master

env:
  global:
    secure: iGeUXCPSD1bpodepRM80hYpNI41YsijSrZQa+Nb3KLAWdHpDszVfG9K7Na5Tn98s3xCvgAQNz8Gt+6OIF5hakj7h0O+8vl2ziPR3dhqeYPkOVOaojmhjux+c9HABL5hhu3M5Eqph58+RpdAAzwnzmA0ctBsggOIzqOWFphm0Fmcz4V34vuWPJiWRBBKBffvH+7l60uagHlByF9S+xrDW2poXcO0y6WNzXsiYyDIsEOsrXDdFiMAVJA5eOFNMur57MF6tjP7Fc02iAdGXVtTlG/4MrvQRiPHRZNkOLfAGML6pVf/qkJqgIWqtJ+tNBgHQsFW6I24sCPQz16oUcHWs7BxNBFmt4yN49uCQmFIJDAq0xguCswfB/Ahki2bs1LPN+OCHW2iU4gHmTeZC8ZGQYf3+qepOakW2khZGgoUEH3Ruw7tvv72oaJHVdJ9hN8JciuIILeeSxDHh1iG4sv9m2tUtwckV4Ml9EGx8CPfSU47rZZKGjd4+2QqyAGJawIpzkrFjHMH+UBh8+efwZDOPZ+iIUT7D/HE370sFUwkMtNCIntwFWXwMZdVvzvD5k6sw8tFK9NMqAg0KHJC0kPhtMzZelRhanlpeIr4YNsZU9Spk1VHTiPUR6Y9zVPBKST7X3pIwcUcxcCeuUmh7ybncxsJpGV0fT/093N3RaQMM7pk=
